<a href="https://colab.research.google.com/github/aibees/anaconda_prods/blob/main/Logistic%20Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from statsmodels.api import Logit
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [3]:
df = pd.read_csv("iris.csv")

In [4]:
df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df["Species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
df["is_setosa"] = (df["Species"] == "setosa") + 0

In [7]:
model = Logit(endog = df["is_setosa"],
              exog = df.iloc[:, :2]).fit() # sepal.length / sepal.width / petal.length / petal.width 4개 컬럼을 독립변수로 적용

Optimization terminated successfully.
         Current function value: 0.036374
         Iterations 11


In [8]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:              is_setosa   No. Observations:                  150
Model:                          Logit   Df Residuals:                      148
Method:                           MLE   Df Model:                            1
Date:                Tue, 17 Aug 2021   Pseudo R-squ.:                  0.9429
Time:                        11:36:21   Log-Likelihood:                -5.4560
converged:                       True   LL-Null:                       -95.477
Covariance Type:            nonrobust   LLR p-value:                 4.745e-41
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Sepal.Length    -7.5299      2.252     -3.343      0.001     -11.945      -3.115
Sepal.Width     13.1307      3.987      3.294      0.001       5.317      20.945
================================================================================

Possibly complete quasi-separation: A fraction 0.43 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

In [9]:
model.params

Sepal.Length    -7.529945
Sepal.Width     13.130734
dtype: float64

In [10]:
model.tvalues

Sepal.Length   -3.343109
Sepal.Width     3.293594
dtype: float64

In [11]:
model.pvalues

Sepal.Length    0.000828
Sepal.Width     0.000989
dtype: float64

In [12]:
model.tvalues

Sepal.Length   -3.343109
Sepal.Width     3.293594
dtype: float64

In [13]:
model.predict(df.iloc[:5, :2])

0    0.999477
1    0.923824
2    0.998678
3    0.997688
4    0.999934
dtype: float64

In [14]:
model_r = LogisticRegression(random_state=123)
model_r.fit(X = df.iloc[:, :2], y = df["is_setosa"])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
model_r.coef_ # 계수

array([[-3.38829757,  3.1645277 ]])

In [16]:
model_r.intercept_ # 절편

array([8.32330389])

In [19]:
# 예측
pred = model_r.predict_proba(df.iloc[:, :2])
pred = pred[:, 1]
pred

array([8.92720238e-01, 7.71046348e-01, 9.25861792e-01, 9.27383226e-01,
       9.41260955e-01, 9.14366510e-01, 9.70588854e-01, 8.94844544e-01,
       9.30340069e-01, 8.22106028e-01, 8.50082658e-01, 9.43687032e-01,
       8.25355057e-01, 9.62572636e-01, 7.90722967e-01, 9.49498438e-01,
       9.14366510e-01, 8.92720238e-01, 7.37925296e-01, 9.55561442e-01,
       6.86948409e-01, 9.40011474e-01, 9.84162879e-01, 8.15466254e-01,
       9.43687032e-01, 7.05867903e-01, 8.94844544e-01, 8.55697295e-01,
       8.12075145e-01, 9.25861792e-01, 8.66401735e-01, 6.86948409e-01,
       9.75366839e-01, 9.51601779e-01, 8.22106028e-01, 8.18809824e-01,
       6.82116219e-01, 9.57423588e-01, 9.48259025e-01, 8.58438460e-01,
       9.21120027e-01, 5.87678957e-01, 9.71839851e-01, 9.21120027e-01,
       9.55561442e-01, 8.25355057e-01, 9.55561442e-01, 9.46018652e-01,
       8.88358175e-01, 8.61136004e-01, 5.12600003e-03, 3.78582845e-02,
       5.24138947e-03, 4.59168341e-02, 7.84539075e-03, 1.06280067e-01,
      

In [20]:
thredhold = 0.5
(pred > thredhold) + 0

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
from sklearn.metrics import roc_auc_score

In [22]:
roc_auc_score(y_true=df["is_setosa"], y_score = pred) # 최대 1, 최소 0.5

1.0

In [24]:
accuracy_score(y_true = df["is_setosa"],
               y_pred = (pred > 0.8) + 0)

0.9466666666666667

In [41]:
#question
from sklearn.model_selection import train_test_split
data = pd.read_csv("diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [42]:
data_sub = data[["BloodPressure", "Glucose", "BMI", "Insulin", "Outcome"]]

In [43]:
data_sub.head()

BloodPressure  Glucose   BMI  Insulin  Outcome
0             72      148  33.6        0        1
1             66       85  26.6        0        0
2             64      183  23.3        0        1
3             66       89  28.1       94        0
4             40      137  43.1      168        1

In [44]:
d_train, d_test = train_test_split(data_sub, train_size = 0.8, random_state = 123)

In [45]:
model = Logit(endog = d_train["Outcome"],
              exog = d_train.iloc[:, :4]).fit()

Optimization terminated successfully.
         Current function value: 0.626579
         Iterations 5


In [46]:
pred = model.predict(d_test.iloc[:, :4])

In [47]:
pred = (pred > 0.5) + 0

In [39]:
pred

236    0
395    0
36     0
210    0
483    0
      ..
650    0
579    0
119    0
593    0
310    0
Length: 154, dtype: int64

In [48]:
accuracy_score(d_test["Outcome"], pred)

0.7012987012987013

In [61]:
# 승산비 구하기
data = pd.read_csv("diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [62]:
data_sub2 = data[["Glucose", "BMI", "Age", "Outcome"]]

In [63]:
model2 = Logit(endog = data_sub2["Outcome"],
               exog = data_sub2.iloc[:, :3]).fit()

Optimization terminated successfully.
         Current function value: 0.656276
         Iterations 4


In [64]:
model2.params

Glucose    0.009368
BMI       -0.035639
Age       -0.012898
dtype: float64

In [65]:
import numpy as np
np.exp(model2.params)

Glucose    1.009412
BMI        0.964989
Age        0.987184
dtype: float64

In [66]:
#AUC
data.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [76]:
data_sub3 = data[["Glucose", "BMI", "Age", "Outcome"]]

In [83]:
data_sub3.iloc[:, :3]

Glucose   BMI  Age
0        148  33.6   50
1         85  26.6   31
2        183  23.3   32
3         89  28.1   21
4        137  43.1   33
..       ...   ...  ...
763      101  32.9   63
764      122  36.8   27
765      121  26.2   30
766      126  30.1   47
767       93  30.4   23

[768 rows x 3 columns]

In [78]:
model4 = Logit(endog = data_sub3["Outcome"],
               exog = data_sub3.iloc[:, :3]).fit()

Optimization terminated successfully.
         Current function value: 0.656276
         Iterations 4


In [84]:
pred = model4.predict(data_sub3.iloc[:, :3])

In [85]:
pred

0      0.387961
1      0.365506
2      0.615678
3      0.392087
4      0.336654
         ...   
763    0.261357
764    0.373590
765    0.453351
766    0.377879
767    0.375465
Length: 768, dtype: float64

In [86]:
roc_auc_score(y_true = data_sub3["Outcome"], y_score = pred)

0.5414253731343283